import { Data } from '../types';

export const data: Data = {
  'zh-CN': {
    H1: '一级标题',
    H2: '二级标题',
    H3: '三级标题',
    H4: '四级标题',
    H5: '五级标题',
    H6: '六级标题',
    Bold: '加粗',
    Italic: '斜体',
    Underline: '下划线',
    StrikeThrough: '删除线',
    Blockquote: '引用',
    OrderedList: '有序列表',
    TaskList: '任务列表',
    Horizontal: '分割线',
    UnorderedList: '无序列表',
    CodeBlock: '代码块',
    InlineCode: '行内代码',
    left: '左对齐',
    center: '居中对齐',
    right: '右对齐',
  },
  'en-US': {
    H1: 'H1',
    H2: 'H2',
    H3: 'H3',
    H4: 'H4',
    H5: 'H5',
    H6: 'H6',
    Bold: 'Bold',
    Italic: 'Italic',
    Underline: 'Underline',
    StrikeThrough: 'StrikeThrough',
    Blockquote: 'Blockquote',
    OrderedList: 'OrderedList',
    TaskList: 'TaskList',
    Horizontal: 'Horizontal',
    UnorderedList: 'UnorderedList',
    CodeBlock: 'CodeBlock',
    InlineCode: 'InlineCode',
    left: 'left',
    center: 'center',
    right: 'right',
  },
};
