import { Data } from '../types';

export const data: Data = {
  'zh-CN': {
    header: {
      H1: '一级标题',
      H2: '二级标题',
      H3: '三级标题',
      H4: '四级标题',
      H5: '五级标题',
      H6: '六级标题',
      Bold: '加粗',
      Italic: '斜体',
      Underline: '下划线',
      StrikeThrough: '删除线',
      Blockquote: '引用',
      OrderedList: '有序列表',
      TaskList: '任务列表',
      Horizontal: '分割线',
      UnorderedList: '无序列表',
      CodeBlock: '代码块',
      InlineCode: '行内代码',
      left: '左对齐',
      center: '居中对齐',
      right: '右对齐',
    },
    helper: {
      help: '帮助',
      Blod: '加粗',
      Italic: '斜体',
      Underline: '下划线',
      StrikeThrough: '删除线',
      Code: '行内代码',
      'normal text': '正常文本',
      'heading one': '一级标题',
      'heading two': '二级标题',
      'heading three': '三级标题',
      'heading four': '四级标题',
      'heading five': '五级标题',
      'heading six': '六级标题',
      'Ordered list': '有序列表',
      'Bullet list': '无序列表',
      'Task list': '任务列表',
      Blockquote: '引用',
      'Left Align': '左对齐',
      'Center Align': '居中对齐',
      'Right Align': '右对齐',
      'Code Block': '代码块',
      Help: '帮助',
    },
  },
  'en-US': {
    header: {
      H1: 'H1',
      H2: 'H2',
      H3: 'H3',
      H4: 'H4',
      H5: 'H5',
      H6: 'H6',
      Bold: 'Bold',
      Italic: 'Italic',
      Underline: 'Underline',
      StrikeThrough: 'StrikeThrough',
      Blockquote: 'Blockquote',
      OrderedList: 'OrderedList',
      TaskList: 'TaskList',
      Horizontal: 'Horizontal',
      UnorderedList: 'UnorderedList',
      CodeBlock: 'CodeBlock',
      InlineCode: 'InlineCode',
      left: 'left',
      center: 'center',
      right: 'right',
    },
    helper: {
      help: 'help',
      Blod: 'Blod',
      Italic: 'Italic',
      Underline: 'Underline',
      StrikeThrough: 'StrikeThrough',
      Code: 'Code',
      'normal text': 'Normal text',
      'heading one': 'Heading one',
      'heading two': 'Heading two',
      'heading three': 'Heading three',
      'heading four': 'Heading four',
      'heading five': 'Heading five',
      'heading six': 'Heading six',
      'Ordered list': 'Ordered list',
      'Bullet list': 'Bullet list',
      'Task list': 'Task list',
      Blockquote: 'Blockquote',
      'Left Align': 'Left Align',
      'Center Align': 'Center Align',
      'Right Align': 'Right Align',
      'Code Block': 'Code Block',
      Help: 'help',
    },
  },
};
